apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
      - image: europe-southwest1-docker.pkg.dev/microservicios-444417/imagen-registro/auth-ms
        name: auth-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          value: "mongodb+srv://root-user:ItqRgCRtrz7PFLCY@auth-microservice-db.5h6tt.mongodb.net/AuthDB"
        - name: JWT_SECRET
          value: "OtroStringSeguroIriaAQUI"
        resources: {}
status: {}